# Generated by Django 5.0.6 on 2026-08-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='raw_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('razorpay', 'Razorpay (UPI, Cards, NetBanking)'), ('stripe', 'Stripe (Cards & Digital Wallets)'), ('upi', 'UPI Direct'), ('card', 'Credit / Debit Card'), ('paypal', 'PayPal')], default='cod', max_length=20),
        ),
    ]
